#!/usr/bin/env php
<?php

use App\Authorization\CreateUserCommand;
use Silly\Application;

$container = require __DIR__ . '/boot.php';

$app = $container->get(Application::class);
assert($app instanceof Application);

$app->useContainer($container);

$app->command('create-user', CreateUserCommand::class);

$app->run();
