#!/usr/bin/env bash

yarn;

npx tailwindcss -i ./main.css -o ./public/main.css

composer install;

if [ ! -f src/Persistence/sqlite.db ]; then
    cp src/Persistence/sqlite-starter.db src/Persistence/sqlite.db;
fi

cd public;
php -S localhost:8000;
