<?php

use App\App;
use BuzzingPixel\Templating\TemplateEngine;

/** @phpstan-ignore-next-line */
assert($this instanceof TemplateEngine);

$this->extends(App::PATH . '/Layout.phtml');
?>

<div class="mx-auto max-w-2xl">
    <div class="p-1 m-4">
        <form
            action="/notes/add"
            class="relative"
            method="POST"
        >
            <div class="overflow-hidden rounded-lg border border-gray-300 shadow-sm focus-within:border-indigo-500 focus-within:ring-1 focus-within:ring-indigo-500">
                <label for="title" class="sr-only">Title</label>
                <input type="text" name="title" id="title" class="block w-full border-0 pt-2.5 text-lg font-medium placeholder:text-gray-400 focus:ring-0" placeholder="Title">
                <label for="description" class="sr-only">Note</label>
                <textarea rows="8" name="note" id="description" class="block w-full resize-none border-0 py-0 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" placeholder="Write your note..."></textarea>
                <div aria-hidden="true">
                    <div class="py-2">
                        <div class="h-9"></div>
                    </div>
                    <div class="h-px"></div>
                    <div class="py-2">
                        <div class="py-px">
                            <div class="h-9"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="absolute inset-x-px bottom-0">
                <div class="border-t border-gray-200 px-2 py-2 sm:px-3">
                    <div class="text-right">
                        <a href="/notes" class="rounded-full border border-gray-200 px-4 py-2.5 text-sm font-semibold text-gray-900 shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Cancel</a>
                        <button type="submit" class="rounded-full bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Create</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
