<?php

use App\App;
use App\Notes\Note;
use App\Notes\NoteCollection;
use BuzzingPixel\Templating\TemplateEngine;

/** @phpstan-ignore-next-line */
assert($this instanceof TemplateEngine);

/**
 * @phpstan-ignore-next-line
 * @noinspection PhpUndefinedVariableInspection
 */
assert($notes instanceof NoteCollection);

$this->extends(App::PATH . '/Layout.phtml');
?>

<div class="mx-auto max-w-2xl">
    <?php if ($notes->isNotEmpty()): ?>
        <div class="p-1 m-4 text-right">
            <a
                href="/notes/add"
                class="inline-flex items-center rounded-full bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
            >
                <svg class="-ml-0.5 mr-1.5 h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
                </svg>
                Add Note
            </a>
        </div>
    <?php endif; ?>
    <div class="p-4 border border-gray-100 rounded-md shadow-md m-4">
        <?php if ($notes->isEmpty()): ?>
            <div class="text-center">
                <h3 class="mt-2 text-sm font-semibold text-gray-900">No Notes</h3>
                <p class="mt-1 text-sm text-gray-500">Get started by creating one.</p>
                <div class="mt-6">
                    <a
                        href="/notes/add"
                        class="inline-flex items-center rounded-full bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                    >
                        <svg class="-ml-0.5 mr-1.5 h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
                        </svg>
                        Add Note
                    </a>
                </div>
            </div>
        <?php else: ?>
            <ul role="list" class="divide-y divide-gray-100">
                <?php
                $notes->map(static function (Note $note) {
                    ?>
                    <li class="flex items-center justify-between gap-x-6 py-5">
                        <div class="flex min-w-0 gap-x-4">
                            <div class="min-w-0 flex-auto">
                                <p class="text-sm font-semibold leading-6 text-gray-900">
                                    <?=$note->title->toNative()?>
                                </p>
                            </div>
                        </div>
                        <div>
                            <div class="inline-block">
                                <form
                                    action="/notes/delete"
                                    method="POST"
                                >
                                    <input type="hidden" name="id" value="<?=$note->id->toNative()?>">
                                    <button
                                        type="submit"
                                        class="rounded-full bg-white px-2.5 py-1 text-xs font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
                                    >
                                        Delete
                                    </button>
                                </form>
                            </div>
                            <div class="inline-block">
                                <a
                                    href="/notes/view/<?=$note->id->toNative()?>"
                                    class="rounded-full bg-white px-2.5 py-1 text-xs font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
                                >
                                    View
                                </a>
                            </div>
                        </div>
                    </li>
                    <?php
                })
                ?>
            </ul>
        <?php endif; ?>
    </div>
</div>
