<?php

use App\App;
use BuzzingPixel\Templating\TemplateEngine;

/** @phpstan-ignore-next-line */
assert($this instanceof TemplateEngine);

$this->extends(App::PATH . '/Layout.phtml');
?>

<main class="relative isolate min-h-full">
    <img src="https://images.unsplash.com/photo-1545972154-9bb223aac798?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=3050&q=80&exp=8&con=-15&sat=-75" alt="" class="absolute inset-0 -z-10 h-full w-full object-cover object-top">
    <div class="mx-auto max-w-7xl px-6 py-32 text-center sm:py-40 lg:px-8">
        <h1 class="mt-4 text-3xl font-bold tracking-tight text-white sm:text-5xl">Hello World</h1>
        <p class="mt-4 text-base text-white/70 sm:mt-6">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
</main>
