<?php

use BuzzingPixel\Templating\TemplateEngine;

/** @phpstan-ignore-next-line */
assert($this instanceof TemplateEngine);
?>
<!doctype html>
<html lang="" class="h-full">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/main.css" rel="stylesheet">
    <title>Hello World</title>
</head>
<body class="h-full">
<?= $this->getSection('layoutContent') ?>
</body>
</html>
